from typing import Dict

FIX_TAGS: Dict[str, int] = {
    "ioi_id": 23,
    "ioi_trans_type": 28,
    "ioi_ref_id": 26,
    "symbol": 55,
    "no_underlyings": 711,
    "side": 54,
    "qty_type": 854,
    "ioi_qty": 27,
    "currency": 15,
    "no_legs": 555,
    "price_type": 423,
    "price": 44,
    "valid_until_time": 62,
    "ioi_qlty_ind": 25,
    "ioi_natural_flag": 130,
    "no_ioi_qualifiers": 199,
    "text": 58,
    "encoded_text_len": 354,
    "encoded_text": 355,
    "transact_time": 60,
    "url_link": 149,
    "no_routing_ids": 215,
    "routing_type": 216,
    "routing_id": 217,
    "checksum": 10,
}
